[
    {
      "id": 1,
      "nombre": "Juan Pérez",
      "cargo": "Gerente de Ventas",
      "departamento": "Ventas",
      "salario": 1000000,
      "nacionalidad": "Española",
      "etnia": "Caucásica",
      "género": "Hombre",
      "fecha_nacimiento": "1980-01-01",
      "imagen": "../assets/portrait/JuanPerez.webp",
      "personal_a_cargo": [2, 3],
      "usuario": "juan.perez",
      "contrasena": "123456"
    },
    {
      "id": 2,
      "nombre": "María González",
      "cargo": "Desarrollador de Software",
      "departamento": "Tecnología",
      "salario": 800000,
      "nacionalidad": "Mexicana",
      "etnia": "Mestiza",
      "género": "Mujer",
      "fecha_nacimiento": "1985-05-05",
      "imagen": "../assets/portrait/MariaGonzalez.webp",
      "personal_a_cargo": [],
      "usuario": "maria.gonzalez",
      "contrasena": "abcdef"
    },
    {
      "id": 3,
      "nombre": "Pedro López",
      "cargo": "Analista de Datos",
      "departamento": "Finanzas",
      "salario": 700000,
      "nacionalidad": "Chilena",
      "etnia": "Mapuche",
      "género": "Hombre",
      "fecha_nacimiento": "1990-10-10",
      "imagen": "../assets/portrait/PedroLopez.webp",
      "personal_a_cargo": [],
      "usuario": "pedro.lopez",
      "contrasena": "ghijkl"
    },
    {
      "id": 4,
      "nombre": "Ana Martínez",
      "cargo": "Diseñadora Gráfica",
      "departamento": "Marketing",
      "salario": 600000,
      "nacionalidad": "Argentina",
      "etnia": "Italiana",
      "género": "Mujer",
      "fecha_nacimiento": "1995-03-03",
      "imagen": "../assets/portrait/AnaMartinez.webp",
      "personal_a_cargo": [],
      "usuario": "ana.martinez",
      "contrasena": "mnopqr"
    },
    {
      "id": 5,
      "nombre": "Luis García",
      "cargo": "Ingeniero de Software",
      "departamento": "Tecnología",
      "salario": 900000,
      "nacionalidad": "Colombiana",
      "etnia": "Afrodescendiente",
      "género": "Hombre",
      "fecha_nacimiento": "1988-08-08",
      "imagen": "../assets/portrait/LuisGarcia.webp",
      "personal_a_cargo": [],
      "usuario": "luis.garcia",
      "contrasena": "stuvwxy"
    },

    {
        "id": 6,
        "nombre": "Sofía Ramírez",
        "cargo": "Gerente de Recursos Humanos",
        "departamento": "Recursos Humanos",
        "salario": 1200000,
        "nacionalidad": "Peruana",
        "etnia": "Quechua",
        "género": "Mujer",
        "fecha_nacimiento": "1975-07-07",
        "imagen": "../assets/portrait/SofiaRamirez.webp",
        "personal_a_cargo": [7, 8],
        "usuario": "sofia.ramirez",
        "contrasena": "12345678"
      },
      {
        "id": 7,
        "nombre": "David Torres",
        "cargo": "Asistente de Recursos Humanos",
        "departamento": "Recursos Humanos",
        "salario": 500000,
        "nacionalidad": "Ecuatoriana",
        "etnia": "Mestiza",
        "género": "Hombre",
        "fecha_nacimiento": "2000-01-01",
        "imagen": "../assets/portrait/DavidTorres.webp",
        "personal_a_cargo": [],
        "usuario": "david.torres",
        "contrasena": "zxcvbnm"
      },
      {
        "id": 8,
        "nombre": "Camila Díaz",
        "cargo": "Recepcionista",
        "departamento": "Recepción",
        "salario": 400000,
        "nacionalidad": "Venezolana",
        "etnia": "Indígena",
        "género": "Mujer",
        "fecha_nacimiento": "2002-04-04",
        "imagen": "../assets/portrait/CamilaDiaz.webp",
        "personal_a_cargo": [],
        "usuario": "camila.diaz",
        "contrasena": "qazwsxedc"
      },
      {
        "id": 9,
        "nombre": "Santiago Castro",
        "cargo": "Contador",
        "departamento": "Finanzas",
        "salario": 800000,
        "nacionalidad": "Dominicana",
        "etnia": "Mulata",
        "género": "Hombre",
        "fecha_nacimiento": "1992-12-12",
        "imagen": "../assets/portrait/SantiagoCastro.webp",
        "personal_a_cargo": [],
        "usuario": "santiago.castro",
        "contrasena": "1234567890"
      },
      {
        "id": 10,
        "nombre": "Isabella Fernández",
        "cargo": "Gerente de Marketing",
        "departamento": "Marketing",
        "salario": 1100000,
        "nacionalidad": "Uruguaya",
        "etnia": "Europea",
        "género": "Mujer",
        "fecha_nacimiento": "1983-06-06",
        "imagen": "../assets/portrait/IsabellaFernandez.webp",
        "personal_a_cargo": [4],
        "usuario": "isabella.fernandez",
        "contrasena": "abcdefghi"
      }
]


  